apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: vault
  template:
    metadata:
      labels:
        name: vault
        service: vault
    spec:
      securityContext:
        runAsUser: 1026
        runAsGroup: 100
      volumes:
      - name: data
        nfs:
          server: nas.local
          path: /volume1/farm/vault
      - name: secrets
        secret:
          secretName: vault
      containers:
      - name: vault
        image: arecker/vault:v0.17.0
        command: ["entry.sh", "server"]
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: data
          mountPath: /data
      - name: terraform
        image: arecker/vault:v0.17.0
        command: ["entry.sh", "terraform"]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: secrets
          mountPath: /secrets
      - name: unseal
        image: arecker/vault:v0.17.0
        command: ["entry.sh", "unseal"]
        volumeMounts:
        - name: secrets
          mountPath: /secrets
