apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault
  template:
    metadata:
      labels:
        name: vault
        service: vault
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      volumes:
      - name: data
        nfs:
          server: archive.local
          path: /mnt/scratch/farm/vault
      - name: secrets
        secret:
          secretName: vault
      containers:
      - name: vault
        image: arecker/vault:v0.10.3
        command: ["entry.sh", "server"]
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: data
          mountPath: /data
      - name: terraform
        image: arecker/vault:v0.10.3
        command: ["entry.sh", "terraform"]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: secrets
          mountPath: /secrets
