apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault
  template:
    metadata:
      labels:
        name: vault
        service: vault
    spec:
      volumes:
      - name: data
        nfs:
          server: archive.local
          path: /mnt/scratch/farm/vault
      containers:
      - name: vault
        image: arecker/vault:v0.3.0
        command: ["server"]
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        ports:
        - containerPort: 8200
        volumeMounts:
        - name: data
          mountPath: /data
