---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  selector:
    service: vault
  ports:
  - port: 8200
    protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  rules:
  - host: vault.local
    http:
      paths:
      - backend:
          serviceName: vault
          servicePort: 8200
